- debug:
    msg: "restoring from /backup/{{rollback_date}}/{{inventory_hostname}}.txt"

- name: restore the config with merge config
  cisco.ios.config:
    src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"
  when: restore_mode | default('merge') == "merge"

- name: overwrite the config, this will reboot cisco IOS device
  block:
    # this causes Exception received: /builddir/build/BUILD/Python-3.8.8/Objects/dictobject.c:1438: bad argument to internal function
    # - name: copy file over to flash on network device
    #   ansible.netcommon.net_put:
    #     src: "/tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt"
    #     dest: "flash:{{ rollback_date }}-{{ inventory_hostname }}.txt"

    # - name: copy file over to flash on network device
    #   ansible.builtin.command: "scp -o StrictHostKeyChecking=no -i {{ ansible_ssh_private_key_file }} /tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt {{ inventory_hostname }}:flash:{{ rollback_date }}-{{ inventory_hostname }}.txt"
    #   delegate_to: localhost

    # - name: copy file over to flash on network device
    #   ansible.builtin.command: "scp -o StrictHostKeyChecking=no -i {{ playbook_dir }}/tmp/ssh_key }} /tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt {{ inventory_hostname }}:flash:{{ rollback_date }}-{{ inventory_hostname }}.txt"
    #   delegate_to: localhost
    # - name: Pause for 30 minutes
    #   ansible.builtin.pause:
    #     minutes: 30

    - name: copy file over to flash on network device
      ansible.builtin.command: "scp -o StrictHostKeyChecking=no /tmp/{{ rollback_date }}/{{ inventory_hostname }}.txt {{ ansible_user }}@{{ inventory_hostname }}:flash:{{ rollback_date }}-{{ inventory_hostname }}.txt"
      delegate_to: localhost

    - name: overwrite startup config and reboot
      cisco.ios.ios_command:
        commands:
          - command: 'copy flash://{{ rollback_date }}-{{ inventory_hostname }}.txt startup-config'
            prompt:
              - Destination filename
            answer:
             - y
          - command: 'reload'
            prompt:
              - Save?
              - confirm
            answer:
             - y
             - y
    - name: reset the connection
      meta: reset_connection

    - name: Wait for the network device to reload
      wait_for_connection:
        delay: 20
  when: restore_mode | default('merge') == "overwrite"

- name: print to terminal window
  debug:
    msg: "Restore is complete for device {{ inventory_hostname }} is set to {{ rollback_date }} timestamp, restored with restore_mode {{ restore_mode | default('merge') }} "
